### ISSUE TITLE
Operations table getting bigger

### ISSUE THREAD

**Issue by juanogcx** [stefffdev/NubeSync#11]
Hi @stefffdev. I'm starting to have a concern about the size of the operations table on sqlserver. Do you have any suggestion on how the table can be cleared regularly?

**Comment by stefffdev** [comment]
Hi @juanogcx! 

The operations are kept for two reasons:

1. To query if a record was last changed by a differnent user, to only include those in the data  when a client pulls (as described in https://github.com/stefffdev/NubeSync/wiki/Don't-download-unnecessary-records-when-syncing)
2. To query when a property was changed the last time, so on a sync it can be determined if the changes the client currently pushes are already outdated (= someone changed the field later)

So because (1) only brings little advantage don't use "LastChangedByOthers" in your items controller, then it is possible to delete older operations.

The only downside when you delete operations that are let's say older than one week is that when a user who didn't sync for two weeks pushes changes that were made two weeks ago, those changes would overwrite changes that were made 8 days ago (since there are no more operations for that changes), although the changes pushed are older - but only when no changes were made in the last week. 
A complicated topic, but I hope you get what I mean.

So depending on your use-case you could delete operations older than X days, and if you totally don't want users who didn't sync for longer than X days to overwrite values you could handle that on the client side and just discard those old changes directly in the client app.

Let me know when you need any more clarification on this!

**Comment by juanogcx** [comment]
Thanks @stefffdev. Ok so point 1) I understand is already deprecated so no worries about that. Yeah point 2) all clear about that. I was just worried about getting to the point of having a gigantic database if the system gets popular ( which is the idea )

So my follow up question would be:

Do you recommend wiping the local data entirely, on background, at the app launch, or even periodically while running? 

And that leads to another follow up question. The scenario is: 
User has device X and device Y. Both devices and synced. Then, device Y deletes a record. How can device X detect the change and delete the record? It doesn’t seem to work. The record stays forever on device X. So, to support that: will I need to wipe the data regularly? ( that is the way that azure mobile dataservices library works) 

Thanks!

**Comment by stefffdev** [comment]
You could implement it like this:

* store the timestamp of the last sync on the device
* on sync check if the last sync was longer than let's say a month ago, then purge all changes (= delete all records from the operation table in the datastore on the client)
* this allows you then to regularly delete all operations older than a month on the server

Regarding your second question:

When Y deletes a record it will get the "deletedAt" field set on the server.
X then syncs and receives the record and deletes it from the local store because "deletedAt" is set.

There should be no need to wipe the local datastore for this.

**Comment by juanogcx** [comment]
Thanks @stefffdev for all your feedback. All good. I tried the deleting "propagation" between devices and it's working on latest version of nubesync.
