### ISSUE TITLE
Offline Blazor client sample

### ISSUE THREAD

**Issue by boskoKlemenc** [stefffdev/NubeSync#22]
Hello, 

I would kindly ask if there is a sample how to sync clients SQLite database with the database on the server. 

Best regards,
Bostjan

**Comment by stefffdev** [comment]
Hi, currently I‘m relying on a sqlite database for storing the offline data, but sqlite does not work in Blazor wasm as far as I know.

One would have to implement the offline store using something like IndexedDb instead of sqlite, then the sync would also work in Blazor wasm.

But since we don‘t use Blazor in such a project we don‘t have that on our roadmap currently - although this might change in the future.

**Comment by boskoKlemenc** [comment]
Hi Stefffdev, 

thanks for your instant reply. 
I will try the IndexedDB to store data offline and I will implement some logic to check when server is online and push the local data to the server and vice versa. 

Regards,
Bostjan

**Comment by stefffdev** [comment]
Hi Bostjan,

let me know if you manage to implement IDataStore using IndexedDB - if you want to share it we could integrate it in the NubeSync repo, I'm sure there are others out there that want you make offline enabled Blazor apps: 😀

**Comment by boskoKlemenc** [comment]
The BlazorIndexDB fork from Nathan Westfall seems to be working with wasm as I tried it, the original fork seems to be outdated.

**Comment by stefffdev** [comment]
Nice, let me know if you run into any problems or when you have something to share! ;-)
Closing this for now.

**Comment by madffm** [comment]
Hi,

I'm curious if there is an working example for Blazor offline with sqlite by now :)

Best regards
Matthias

**Comment by stefffdev** [comment]
Hi, unfortunately not as far as I know - I never tried it myself and haven‘t heard from anybody else implementing it!
