### ISSUE TITLE
DateTimeOffset is not supported in MariaDB/MySQL database

### ISSUE THREAD

**Issue by jantech** [stefffdev/NubeSync#39]
Hi Team,

Thanks for the great effort.

As I noticed, When I try to configure mysql database, I couldn't migrate the DB successfully. 
Could you please provide support to MariaDB / MySQL databases would be great addon. 

Below is the error message getting when running "dotnet ef database update" from command line. 
![image](https://user-images.githubusercontent.com/8392206/190852965-9796b411-09f8-41b0-9e43-9e829786f223.png)

The issue here is , "DateTimeOffset" datatype is not supported in MariaDB/MySQL, its only for MS SQL server. 
Requesting to update the NubeSync package entities to support all kind of database that could .net core entity framework handles.

Kindly check and do the helpful. 

Thanks and Looking forward to hear from you.

**Comment by stefffdev** [comment]
Hi @jantech, thanks for reaching out!

Could you please provide a small sample project with that issue so I can reproduce it?

thanks and kind regards!

**Comment by jantech** [comment]
Hi @stefffdev , thanks for the reply. 

Below is the repository that I tried. https://github.com/jantech/NubeDataSyncSample

Please check and let me know if any details required.

Thanks,
Jagan

**Comment by stefffdev** [comment]
Hi @jantech, thanks for the sample!

I did not have any problems creating the database with MySql version 8 performing the following steps:

- updated the server project to use .NET 6 (not sure if needed, but I do not have .NET 5 installed right now)
- deleted everything from the Migrations folder to have a clean start
- removed the Clustered Index stuff from the DataContext, since this is a MSSQL specific thing as well:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
            base.OnModelCreating(modelBuilder);

            // modelBuilder.Entity<NubeServerOperation>().HasKey(e => e.Id).IsClustered(false);
            // modelBuilder.Entity<NubeServerOperation>().HasIndex(e => e.ClusteredIndex).IsClustered();
            // modelBuilder.Entity<NubeServerOperation>().Property(e => e.ClusteredIndex).ValueGeneratedOnAdd();
            modelBuilder.Entity<NubeServerOperation>().HasIndex(e => new { e.ItemId, e.TableName, e.Property, e.CreatedAt });

            modelBuilder.Entity<NubeServerOperation>().HasIndex(e => new { e.ItemId, e.TableName, e.ServerUpdatedAt, e.ProcessingType, e.InstallationId });
            // modelBuilder.Entity<TodoItem>().HasKey(e => e.Id).IsClustered(false);
            // modelBuilder.Entity<TodoItem>().HasIndex(e => e.ClusteredIndex).IsClustered();
            // modelBuilder.Entity<TodoItem>().Property(e => e.ClusteredIndex).ValueGeneratedOnAdd();
            modelBuilder.Entity<TodoItem>().HasIndex(e => new { e.UserId, e.ServerUpdatedAt });
}
```

Then run **dotnet ef migrations add Initial** and **dotnet ef database update**

If you still run into problems with DateTimeOffset, you can try to map it to another type of field via a ValueConversion, for example as described in https://github.com/dotnet/efcore/issues/6601#issuecomment-554773511 and https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/819#issuecomment-970470053

Let me know if you get it working!

**Comment by jantech** [comment]
Hi @stefffdev,

It worked after following above steps, now I'm able to create database migrations and data stored in MySql database.

Looking forward for more features and support to Flutter and Blazor Client.

Thanks for your support. Please enhance the library with new features and client support.

Thanks,
Jagan

**Comment by stefffdev** [comment]
Hi Jagan,
good to know!

You can find a (rough) Flutter sample here (https://github.com/stefffdev/NubeSync/tree/master/samples/Clients/Flutter/nubesyncflutter) if you haven't found it already.

thx
