### ISSUE TITLE
Pull Operation Failed Exception

### ISSUE THREAD

**Issue by Jcardif** [stefffdev/NubeSync#4]
When trying to sync changes on a Universal Windows app I get this error 

![image](https://user-images.githubusercontent.com/29174946/94799469-d6bf6f00-03eb-11eb-994b-842121cd3681.png)

Upload executes successfully but it crashes on this line of code

```C#
 await _nubeClient.PullTableAsync<ToDOItem>();
```

**Comment by stefffdev** [comment]
Could it be that your class name is different in the client than on the server?
E.g. "ToDOItem" instead of "TodoItem"?

The error basically means that the endpoint on the server cannot be found, if you don't supply a endpoint name in the "AddTableAsync" method on the client the class name is used.
And when that is different on the server that error occurs.

So either rename your class on the client or provide the controller name of the server in the "AddTableAsync" method.

**Comment by Jcardif** [comment]
Thank you. The problem was that my endpoint was /api/[controller] I changed it to [controller] and now everything works well
