### ISSUE TITLE
Related Data

### ISSUE THREAD

**Issue by MarkLFT** [stefffdev/NubeSync#42]
Is this library suitable for syncing related tables, i.e. invoice and invoice items?  In the client when I try to register the tables I receive a NotSupportedException, followed by a Don't know about <class name> message.

I have tried to register the master table first, followed by the detail table, and vice versa, but I receive the same message both ways.

**Comment by stefffdev** [comment]
Hi Mark, 
syncing related tables should not be a problem, can you share some code that causes the "NotSupportedException" or the "Don't know about message"?

**Comment by MarkLFT** [comment]
Many thanks for the prompt feedback.

I am putting together a proof-of-concept type application that incorporates several technologies, multi-tenant and offline sync being the key two.  The repo is at [POSManagerPOC](https://github.com/MarkLFT/POSManagerPOC.git).

The code with the tables is in the integration tests file in the Tests/API.Invoices.Tests/ folder.

Please let me know if I have done anything wrong.  This is all very much a work in progress.

**Comment by stefffdev** [comment]
Thx, I pulled your repo.

The errors you mention come from Sqlite, it is not possible to have "complex types" in the tables, in your case that means the "InvoiceItem" is not allowed to have a "Invoice" Property, since Sqlite only allows "Database Types" like int, string, .... as columns

When you remove the property "Invoice" from InvoiceItem.cs and the property "InvoiceItems" from Invoice.cs the error disappears.

I personally use no complex types on the table classes (the ones that derive from NubeTable) but implement a "InvoiceModel" that holds a list of InvoiceItems - mind that the "InvoiceModel" does not get persisted to the database but the "Invoice".

But it seems you can trick Sqlite into understanding relations (see https://stackoverflow.com/a/55574353) - but I never did it that way myself.

**Comment by MarkLFT** [comment]
We plan to use Uno as our mobile platform, and notice it can use EF Core, which has the ability to use complex models with navigation properties.  How difficult would it be to create a client that uses EF Core on the client end, similar to the way you do on the server end?

**Comment by stefffdev** [comment]
Such a client already exists (although I did not publish it as nuget package): https://github.com/stefffdev/NubeSync/tree/master/src/NubeSync.Client.SQLiteStoreEFCore

You can download the source and see if that works for you!

**Comment by MarkLFT** [comment]
ok, great.  Do you have any notes or blog on using it?

**Comment by stefffdev** [comment]
it's a drop in replacement for the NubeSQLiteDataStore (just use NubeSQLiteDataStoreEFCore instead) and should behave the same.

**Comment by MarkLFT** [comment]
I tried as you suggested, but now getting a different error message, one saying the Invoice table does not exist.  This may be masking the previous error internally.  

I also added a plain EF Core context, with identical models, and it worked fine.  EF Core can have complex graphs and can save and retrieve them.

Not sure if I am doing anything wrong.  I have updated my proof of concept solution, I would be grateful if you could take a look.

**Comment by stefffdev** [comment]
If the error message is "The table type {typeof(T).Name} cannot be found in the data store" then that would mean that the table does not exist in the database itself.

When you add a table to a EF Core Context the table has to be created via migrations, maybe this has not be done yet?
